services:
  - type: web
    name: hybrid-search-mcp
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python hybrid_rag_search_mcp.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 8000
    healthCheckPath: /
